import argparse
import json
import random
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F


try:
    from torch_geometric.data import HeteroData
except ImportError as exc:
    raise ImportError(
        "torch_geometric is required for train_htgnn.py. "
        "Install it in your environment before training."
    ) from exc

from models.legacy_htgnn import LegacyHTGNN
from models.official_htgnn_core import OfficialCoreHTGNN
from utils.evaluation import (
    collect_scores,
    evaluate_regression,
    evaluate_with_threshold,
    resolve_threshold,
    summarize_epoch_metrics,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train HTGNN on temporal heterogeneous snapshots generated by DataPreprocess_new.py"
    )
    parser.add_argument("--data_dir", type=str, default="/data/spz/AHGA/temporal_snapshots")
    parser.add_argument(
        "--test_data_dir",
        type=str,
        default="",
        help="Optional external temporal snapshot directory for final anomaly detection test.",
    )
    parser.add_argument("--seq_len", type=int, default=8)
    parser.add_argument("--train_ratio", type=float, default=0.7)
    parser.add_argument("--val_ratio", type=float, default=0.15)
    parser.add_argument("--hidden_dim", type=int, default=64)
    parser.add_argument("--gru_hidden", type=int, default=64)
    parser.add_argument("--num_layers", type=int, default=1)
    parser.add_argument("--dropout", type=float, default=0.2)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--weight_decay", type=float, default=1e-5)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--patience", type=int, default=10)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--save_path", type=str, default="/data/spz/AHGA/htgnn_best.pt")
    parser.add_argument(
        "--log_file",
        type=str,
        default="",
        help="Optional log file path. If empty, use save_path with .log suffix.",
    )
    parser.add_argument(
        "--device_loss_alpha",
        type=float,
        default=0.3,
        help="Weight of device-only auxiliary BCE loss. Set 0 to disable.",
    )
    parser.add_argument(
        "--decision_mode",
        type=str,
        default="auto",
        choices=["auto", "fixed", "train_quantile"],
        help=(
            "Decision threshold mode for binary prediction: "
            "fixed(0.5), train_quantile(use train score percentile), "
            "auto(use train_quantile when train labels are single-class else fixed)."
        ),
    )
    parser.add_argument(
        "--fixed_threshold",
        type=float,
        default=0.5,
        help="Threshold used when decision_mode=fixed.",
    )
    parser.add_argument(
        "--train_score_quantile",
        type=float,
        default=0.95,
        help="Quantile in [0,1] for threshold estimation on train scores in train_quantile mode.",
    )
    parser.add_argument(
        "--backend",
        type=str,
        default="legacy_pyg",
        choices=["legacy_pyg", "official_htgnn_core"],
        help=(
            "Model backend. legacy_pyg keeps existing SnapshotEncoder+GRU; "
            "official_htgnn_core uses official-style relation/time aggregation core."
        ),
    )
    parser.add_argument(
        "--task_mode",
        type=str,
        default="anomaly_cls",
        choices=["anomaly_cls", "regression"],
        help="Training task mode. anomaly_cls keeps BCE classification; regression uses MAE/MSE target fitting.",
    )
    parser.add_argument(
        "--regression_loss",
        type=str,
        default="l1",
        choices=["l1", "mse"],
        help="Snapshot loss used when task_mode=regression.",
    )
    return parser.parse_args()


class _TeeStream:
    def __init__(self, stream_a, stream_b):
        self.stream_a = stream_a
        self.stream_b = stream_b

    def write(self, data: str) -> int:
        n = self.stream_a.write(data)
        self.stream_b.write(data)
        return n

    def flush(self) -> None:
        self.stream_a.flush()
        self.stream_b.flush()


def enable_log_file(log_path: Path) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    fp = log_path.open("a", encoding="utf-8")
    sys.stdout = _TeeStream(sys.stdout, fp)
    sys.stderr = _TeeStream(sys.stderr, fp)


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def sorted_snapshot_dirs(root: Path) -> List[Path]:
    dirs = [p for p in root.iterdir() if p.is_dir() and p.name.startswith("snapshot_")]
    dirs.sort(key=lambda x: x.name)
    return dirs


def load_one_snapshot(snapshot_dir: Path) -> Tuple[HeteroData, int, Dict]:
    data = HeteroData()

    for node_type in ["crp", "plc", "device"]:
        x_path = snapshot_dir / f"x_{node_type}.npy"
        if not x_path.exists():
            raise FileNotFoundError(f"Missing node feature file: {x_path}")
        x = np.load(x_path)
        data[node_type].x = torch.tensor(x, dtype=torch.float)

    meta_path = snapshot_dir / "hetero_meta.json"
    if not meta_path.exists():
        raise FileNotFoundError(f"Missing hetero_meta.json: {meta_path}")

    with meta_path.open("r", encoding="utf-8") as f:
        meta = json.load(f)

    relations = meta.get("relations", [])
    for rel in relations:
        src_t = rel["src_type"]
        relation = rel["relation"]
        dst_t = rel["dst_type"]
        eidx = np.load(snapshot_dir / rel["edge_index_file"])
        ewt = np.load(snapshot_dir / rel["edge_weight_file"])

        edge_type = (src_t, relation, dst_t)
        data[edge_type].edge_index = torch.tensor(eidx, dtype=torch.long)
        data[edge_type].edge_attr = torch.tensor(ewt.reshape(-1, 1), dtype=torch.float)

    snap_meta_path = snapshot_dir / "snapshot_meta.json"
    if not snap_meta_path.exists():
        raise FileNotFoundError(f"Missing snapshot_meta.json: {snap_meta_path}")

    with snap_meta_path.open("r", encoding="utf-8") as f:
        snap_meta = json.load(f)

    device_gt_npy = snapshot_dir / "device_ground_truth.npy"
    device_gt_csv = snapshot_dir / "device_ground_truth.csv"
    if device_gt_npy.exists():
        device_y = np.load(device_gt_npy).astype(np.float32)
        data["device"].y = torch.tensor(device_y, dtype=torch.float)
    elif device_gt_csv.exists():
        gt_df = np.genfromtxt(device_gt_csv, delimiter=",", names=True, dtype=None, encoding="utf-8")
        if gt_df.size > 0 and "device_label" in gt_df.dtype.names:
            labels = np.atleast_1d(gt_df["device_label"]).astype(np.float32)
            data["device"].y = torch.tensor(labels, dtype=torch.float)

    label = int(snap_meta["snapshot_label"])
    return data, label, snap_meta


def load_snapshots(root: Path) -> Tuple[List[HeteroData], List[int], List[Dict], List[Tuple[str, str, str]]]:
    snapshots = []
    labels = []
    metas = []
    relation_union = set()

    dirs = sorted_snapshot_dirs(root)
    if not dirs:
        raise ValueError(f"No snapshot folders found in {root}")

    for d in dirs:
        data, label, meta = load_one_snapshot(d)
        snapshots.append(data)
        labels.append(label)
        metas.append(meta)
        for et in data.edge_types:
            relation_union.add(et)

    relation_list = sorted(list(relation_union))
    return snapshots, labels, metas, relation_list


def make_sequences(n_snapshots: int, seq_len: int) -> List[List[int]]:
    if n_snapshots < seq_len:
        return []
    seqs = []
    for end in range(seq_len - 1, n_snapshots):
        start = end - seq_len + 1
        seqs.append(list(range(start, end + 1)))
    return seqs


def chronological_split(indices: List[List[int]], train_ratio: float, val_ratio: float):
    n = len(indices)
    n_train = int(n * train_ratio)
    n_val = int(n * val_ratio)

    train_set = indices[:n_train]
    val_set = indices[n_train : n_train + n_val]
    test_set = indices[n_train + n_val :]
    return train_set, val_set, test_set


def run_epoch(
    model: nn.Module,
    sequences: List[List[int]],
    snapshots: List[HeteroData],
    labels: List[int],
    device: torch.device,
    device_loss_alpha: float,
    task_mode: str,
    regression_loss: str,
    optimizer: torch.optim.Optimizer = None,
):
    is_train = optimizer is not None
    model.train() if is_train else model.eval()

    losses = []
    snapshot_losses = []
    device_losses = []
    y_true = []
    y_score = []
    y_true_device = []
    y_score_device = []

    bce_snapshot = nn.BCEWithLogitsLoss()
    bce_device = nn.BCEWithLogitsLoss()
    reg_snapshot = nn.L1Loss() if regression_loss == "l1" else nn.MSELoss()

    for seq in sequences:
        seq_data = [snapshots[i].to(device) for i in seq]
        target = torch.tensor([float(labels[seq[-1]])], dtype=torch.float, device=device)

        with torch.set_grad_enabled(is_train):
            logit, device_logit = model(seq_data)
            if task_mode == "anomaly_cls":
                loss_snapshot = bce_snapshot(logit, target)
                snapshot_score = float(torch.sigmoid(logit).detach().cpu().item())
            else:
                loss_snapshot = reg_snapshot(logit, target)
                snapshot_score = float(logit.detach().cpu().item())
            loss = loss_snapshot

            last_data = seq_data[-1]
            loss_device = None
            if device_loss_alpha > 0 and hasattr(last_data["device"], "y"):
                device_target = last_data["device"].y.view(-1)
                if device_logit.numel() == device_target.numel() and device_target.numel() > 0:
                    loss_device = bce_device(device_logit, device_target)
                    loss = loss + device_loss_alpha * loss_device
                    y_true_device.extend(device_target.detach().cpu().numpy().astype(int).tolist())
                    y_score_device.extend(torch.sigmoid(device_logit).detach().cpu().numpy().tolist())

            if is_train:
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

        losses.append(float(loss.detach().cpu().item()))
        snapshot_losses.append(float(loss_snapshot.detach().cpu().item()))
        if loss_device is not None:
            device_losses.append(float(loss_device.detach().cpu().item()))
        y_true.append(float(target.item()))
        y_score.append(snapshot_score)
    return summarize_epoch_metrics(
        task_mode=task_mode,
        losses=losses,
        snapshot_losses=snapshot_losses,
        device_losses=device_losses,
        y_true=y_true,
        y_score=y_score,
        y_true_device=y_true_device,
        y_score_device=y_score_device,
    )


def main():
    args = parse_args()
    log_path = Path(args.log_file) if args.log_file else Path(args.save_path).with_suffix(".log")
    enable_log_file(log_path)
    print(f"Logging training output to: {log_path}")
    set_seed(args.seed)

    data_root = Path(args.data_dir)
    snapshots, labels, metas, relation_list = load_snapshots(data_root)

    sequences = make_sequences(len(snapshots), args.seq_len)
    if not sequences:
        raise ValueError(
            f"Not enough snapshots ({len(snapshots)}) for seq_len={args.seq_len}."
        )

    train_seqs, val_seqs, split_test_seqs = chronological_split(
        sequences, args.train_ratio, args.val_ratio
    )

    if not train_seqs or not val_seqs:
        raise ValueError(
            "Split produced empty train/val set. "
            "Adjust seq_len/train_ratio/val_ratio."
        )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if args.backend == "legacy_pyg":
        model = LegacyHTGNN(
            node_types=snapshots[0].node_types,
            edge_types=relation_list,
            hidden_dim=args.hidden_dim,
            gru_hidden=args.gru_hidden,
            num_layers=args.num_layers,
            dropout=args.dropout,
        ).to(device)
    else:
        model = OfficialCoreHTGNN(
            node_types=snapshots[0].node_types,
            edge_types=relation_list,
            hidden_dim=args.hidden_dim,
            gru_hidden=args.gru_hidden,
            dropout=args.dropout,
            seq_len=args.seq_len,
        ).to(device)

    optimizer = torch.optim.Adam(
        model.parameters(), lr=args.lr, weight_decay=args.weight_decay
    )

    best_val_metric = -1.0 if args.task_mode == "anomaly_cls" else float("inf")
    best_state = None
    no_improve = 0

    print(f"Model backend: {args.backend}")
    print(f"Task mode: {args.task_mode}")
    if args.backend == "legacy_pyg":
        print("Architecture: SnapshotEncoder(HeteroConv/SAGE) + GRU")
    else:
        print("Architecture: Official-style RelationAgg + TemporalAgg core")
    print(f"Snapshots: {len(snapshots)}, Sequences: {len(sequences)}")
    print(f"Split -> train: {len(train_seqs)}, val: {len(val_seqs)}, split-test: {len(split_test_seqs)}")
    print(f"Device: {device}")
    train_seq_labels = [int(labels[s[-1]]) for s in train_seqs]
    val_seq_labels = [int(labels[s[-1]]) for s in val_seqs]
    print(
        "Label distribution -> "
        f"train attack={sum(train_seq_labels)} normal={len(train_seq_labels)-sum(train_seq_labels)}, "
        f"val attack={sum(val_seq_labels)} normal={len(val_seq_labels)-sum(val_seq_labels)}"
    )
    if len(set(train_seq_labels)) <= 1:
        print(
            "[WARN] Train sequence labels are single-class. "
            "Use --decision_mode train_quantile (or auto) for anomaly-style thresholding."
        )
        if not args.test_data_dir:
            print(
                "[WARN] No --test_data_dir is provided. "
                "For train-all-normal setups, evaluate with an external temporal test set containing attacks."
            )

    for epoch in range(1, args.epochs + 1):
        train_metrics = run_epoch(
            model,
            train_seqs,
            snapshots,
            labels,
            device,
            args.device_loss_alpha,
            args.task_mode,
            args.regression_loss,
            optimizer,
        )
        val_metrics = run_epoch(
            model,
            val_seqs,
            snapshots,
            labels,
            device,
            args.device_loss_alpha,
            args.task_mode,
            args.regression_loss,
            None,
        )

        if args.task_mode == "anomaly_cls":
            print(
                f"Epoch {epoch:03d} | "
                f"train_loss {train_metrics['loss']:.4f} train_f1 {train_metrics['f1']:.4f} train_auprc {train_metrics['auprc']:.4f} train_device_f1 {train_metrics['device_f1']:.4f} | "
                f"val_loss {val_metrics['loss']:.4f} val_f1 {val_metrics['f1']:.4f} val_auprc {val_metrics['auprc']:.4f} val_device_f1 {val_metrics['device_f1']:.4f} val_auc {val_metrics['auc']:.4f}"
            )
            current_metric = val_metrics["f1"]
            improved = current_metric > best_val_metric
        else:
            print(
                f"Epoch {epoch:03d} | "
                f"train_loss {train_metrics['loss']:.4f} train_mae {train_metrics['mae']:.4f} train_rmse {train_metrics['rmse']:.4f} | "
                f"val_loss {val_metrics['loss']:.4f} val_mae {val_metrics['mae']:.4f} val_rmse {val_metrics['rmse']:.4f}"
            )
            current_metric = val_metrics["loss"]
            improved = current_metric < best_val_metric

        if improved:
            best_val_metric = current_metric
            best_state = {
                "model": model.state_dict(),
                "args": vars(args),
                "best_val_metric": best_val_metric,
                "task_mode": args.task_mode,
                "backend": args.backend,
                "relation_list": relation_list,
            }
            no_improve = 0
        else:
            no_improve += 1

        if no_improve >= args.patience:
            print(f"Early stopping at epoch {epoch} (patience={args.patience})")
            break

    if best_state is None:
        raise RuntimeError("Training failed to produce a valid model state.")

    torch.save(best_state, args.save_path)
    print(f"Saved best model to: {args.save_path}")

    model.load_state_dict(best_state["model"])

    test_snapshots = snapshots
    test_labels = labels
    test_sequences = split_test_seqs
    test_tag = "split-test"

    if args.test_data_dir:
        external_root = Path(args.test_data_dir)
        if not external_root.exists():
            print(
                f"[WARN] --test_data_dir does not exist: {external_root}. "
                "Fallback to split-test."
            )
        else:
            try:
                ext_snapshots, ext_labels, _, _ = load_snapshots(external_root)
                ext_sequences = make_sequences(len(ext_snapshots), args.seq_len)
                if not ext_sequences:
                    print(
                        f"[WARN] External test snapshots are insufficient "
                        f"({len(ext_snapshots)}) for seq_len={args.seq_len}. "
                        "Fallback to split-test."
                    )
                else:
                    test_snapshots = ext_snapshots
                    test_labels = ext_labels
                    test_sequences = ext_sequences
                    test_tag = f"external-test ({external_root})"
            except (FileNotFoundError, ValueError) as exc:
                print(
                    f"[WARN] Failed to load external test data from {external_root}: {exc}. "
                    "Fallback to split-test."
                )

    if not test_sequences:
        raise ValueError(
            "No test sequences available. Provide --test_data_dir or adjust split ratios."
        )

    test_metrics = run_epoch(
        model,
        test_sequences,
        test_snapshots,
        test_labels,
        device,
        args.device_loss_alpha,
        args.task_mode,
        args.regression_loss,
        None,
    )

    train_true, train_score = collect_scores(model, train_seqs, snapshots, labels, device, args.task_mode)
    test_true, test_score = collect_scores(model, test_sequences, test_snapshots, test_labels, device, args.task_mode)

    print(f"Test metrics ({test_tag}):")
    if args.task_mode == "anomaly_cls":
        chosen_threshold = resolve_threshold(
            decision_mode=args.decision_mode,
            fixed_threshold=args.fixed_threshold,
            train_score_quantile=args.train_score_quantile,
            train_labels=train_true,
            train_scores=train_score,
        )
        test_decision_metrics = evaluate_with_threshold(test_true, test_score, chosen_threshold)
        print(
            "  "
            + " | ".join(
                [
                    f"loss={test_metrics['loss']:.4f}",
                    f"acc={test_metrics['acc']:.4f}",
                    f"precision={test_metrics['precision']:.4f}",
                    f"recall={test_metrics['recall']:.4f}",
                    f"f1={test_metrics['f1']:.4f}",
                    f"auc={test_metrics['auc']:.4f}",
                    f"auprc={test_metrics['auprc']:.4f}",
                    f"device_f1={test_metrics['device_f1']:.4f}",
                    f"device_auc={test_metrics['device_auc']:.4f}",
                ]
            )
        )
        print(
            "Thresholded test metrics: "
            + " | ".join(
                [
                    f"decision_mode={args.decision_mode}",
                    f"threshold={test_decision_metrics['threshold']:.6f}",
                    f"acc={test_decision_metrics['acc']:.4f}",
                    f"precision={test_decision_metrics['precision']:.4f}",
                    f"recall={test_decision_metrics['recall']:.4f}",
                    f"f1={test_decision_metrics['f1']:.4f}",
                    f"auc={test_decision_metrics['auc']:.4f}",
                    f"auprc={test_decision_metrics['auprc']:.4f}",
                    f"tn={test_decision_metrics['tn']}",
                    f"fp={test_decision_metrics['fp']}",
                    f"fn={test_decision_metrics['fn']}",
                    f"tp={test_decision_metrics['tp']}",
                ]
            )
        )
    else:
        reg_metrics = evaluate_regression(test_true, test_score)
        print(
            "  "
            + " | ".join(
                [
                    f"loss={test_metrics['loss']:.4f}",
                    f"mae={reg_metrics['mae']:.4f}",
                    f"mse={reg_metrics['mse']:.4f}",
                    f"rmse={reg_metrics['rmse']:.4f}",
                    f"device_f1={test_metrics['device_f1']:.4f}",
                    f"device_auc={test_metrics['device_auc']:.4f}",
                ]
            )
        )


if __name__ == "__main__":
    main()
